### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by xackery** [EQMacEmu/quests#1]
griegsend/encounters/traps.lua Undefined global `MobCombatEvent`.
cabwest/Harbinger_Glosk.lua Undefined global `QuestReward`.
grimling/encounters/Necin.lua Undefined field `ForceOpen` (looks like it's being applied to a door_list)
eq.csr_notice is defined, unsure source actually has it
grimling/encounters/Necin.lua:530 Undefined global `JherumWaypointDepart`.

**Comment by regneq** [comment]
those will be fixed shortly.   eq.csr_noticed were left in by accident.  They were removed yesterday.   Thank you for submitting them.

**Comment by Torven** [comment]
The door toggle is working for me.  Several scripts do the same thing.
